#Puerto del microservicio
server:
  port: 8080

#Nombre del microservicio
spring:
  application:
    name: core-transactional

#Configuración de la base de datos corriendo en Docker
datasource:
  url: jdbc:postgresql://localhost:5432/delivery_superapp
  username: superapp_user
  password: superapp_password
  driver-class-name: org.postgresql.Driver

#Configuración de JPA/Hibernate (ORM)
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  show-sql: true # Para ver en la consola las consultas SQL que hace por debajo
  properties:
    hibernate:
      format_sql: true