server:
  port: 8080

spring:
  application:
    name: core-transactional

  datasource:
    url: jdbc:postgresql://localhost:5433/delivery_superapp
    username: superapp_user
    password: Miloj2210_
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.create_namespaces: true

